# Generated by Django 6.0.3 on 2026-04-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('speciality', models.CharField(max_length=100)),
                ('clinic_number', models.CharField(max_length=50)),
                ('schedule', models.TextField()),
                ('appointment_time', models.DateTimeField()),
            ],
        ),
    ]
