# Generated by Django 6.0.3 on 2026-04-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Hospital Doctor', 'verbose_name_plural': 'Hospital Doctors'},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='speciality',
        ),
        migrations.AddField(
            model_name='doctor',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Is Available Now?'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.CharField(default='', help_text='Example: /drNourhan.png', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='next_slot',
            field=models.CharField(default='الآن', max_length=100, verbose_name='Next Available Slot'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='queue_length',
            field=models.IntegerField(default=0, verbose_name='Current Queue'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(default='', max_length=150, verbose_name='Specialty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinic_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Doctor Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='schedule',
            field=models.CharField(max_length=255, verbose_name='Work Schedule'),
        ),
    ]
